name: Publish Website
on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Create-CSS
      run: touch ./css/bulma.css
    - name: Compile-CSS
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: ./css/bulma.scss
        destination: ./css/bulma.css
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: Execute module script 
      run: |
        python .github/module.py
    - name: Reset index.html
      run: git checkout index.html
    - name: FTP-Deploy-Action
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 51.222.31.214
        user: ubuntu
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: var/www/brandonmdavis.com/test3
        forceSsl: true
