name: Publish Website
on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Create-CSS
      run: touch ./css/bulma.css
    - name: Compile-CSS
      uses: gha-utilities/sass-build@v0.2.5
      with:
        source: ./css/bulma.scss
        destination: ./css/bulma.css
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: Execute Module Script # run the run.py to get the latest data
      run: |
        python .github/module.py
    - name: Prepare SSH to work with the remote server
      run: |
        cd ~ && mkdir .ssh &&
        touch ~/.ssh/known_hosts &&
        echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
    - name: SSH-Deploy-Action
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        REMOTE_HOST: 51.222.31.214
        REMOTE_USER: ubuntu
        SSH_PRIVATE_KEY: ${{ secrets.FTP_PASSWORD }}
        TARGET: /var/www/brandonmdavis.com/test3
